dist: trusty
sudo: required
language: python
python:
  - "2.7.14"
# command to install dependencies
install:
  - pip install pylint

script:
  - python test_palindromes.py 
  - pylint palindromes.py

